// Downloads the Higgsfield b-roll listed in clips.json into public/clips/<id>.mp4
// and records which clips are present in src/clips.ts. Scenes fall back to the
// generative canvas world for any clip that is missing, so the reel always renders.
//
//   node scripts/fetch-clips.mjs
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";

const list = JSON.parse(readFileSync(new URL("./clips.json", import.meta.url)));
const dir = new URL("../public/clips/", import.meta.url);
mkdirSync(dir, { recursive: true });
for (const [id, url] of Object.entries(list)) {
  if (id.startsWith("_")) continue;
  const file = new URL(`${id}.mp4`, dir);
  if (existsSync(file)) continue;
  try {
    const res = await fetch(url);
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    writeFileSync(file, Buffer.from(await res.arrayBuffer()));
    console.log("got", id);
  } catch (e) {
    console.warn("skip", id, e.message);
  }
}
const have = Object.keys(list).filter((id) => !id.startsWith("_") && existsSync(new URL(`${id}.mp4`, dir)));
writeFileSync(new URL("../src/clips.ts", import.meta.url),
  `// Generated by scripts/fetch-clips.mjs: b-roll present in public/clips.\nexport const HAVE: string[] = ${JSON.stringify(have)};\n`);
console.log("clips present:", have.length ? have.join(", ") : "none (canvas worlds used)");
